server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-catalog
  zipkin:
    baseUrl: http://localhost:9411/
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  mongodb:
    embedded:
      version: 4.0.2

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      clientCatalogMovie:
        slidingWindowType: COUNT_BASED
        failureRateThreshold: '50'
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        allowHealthIndicatorToFail: 'false'
        registerHealthIndicator: 'true'
        slidingWindowSize: '5'
        permittedNumberOfCallsInHalfOpenState: '2'
        waitDurationInOpenState: '10000'
      clientCatalogSerie:
        slidingWindowType: COUNT_BASED
        failureRateThreshold: '50'
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        allowHealthIndicatorToFail: 'false'
        registerHealthIndicator: 'true'
        slidingWindowSize: '5'
        permittedNumberOfCallsInHalfOpenState: '2'
        waitDurationInOpenState: '10000'
  retry:
    instances:
      retryCatalogMovie:
        maxAttempts: '2'
        waitDuration: '1000'
        retryExceptions[0]: feign.FeignException$InternalServerError
      retryCatalogSerie:
        maxAttempts: '2'
        waitDuration: '1000'
        retryExceptions[0]: feign.FeignException$InternalServerError